# Generated by Django 4.2.5 on 2024-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newFood',
        ),
    ]
